import JSZip from 'jszip';

/**
 * Maps special math unicode symbols commonly generated by Word OMML to LaTeX
 */
function mapOmmlTextToLatex(text: string): string {
  if (!text) return '';
  return text
    .replace(/±/g, ' \\pm ')
    .replace(/×/g, ' \\times ')
    .replace(/÷/g, ' \\div ')
    .replace(/≤/g, ' \\le ')
    .replace(/≥/g, ' \\ge ')
    .replace(/≠/g, ' \\ne ')
    .replace(/≈/g, ' \\approx ')
    .replace(/≡/g, ' \\equiv ')
    .replace(/∞/g, ' \\infty ')
    .replace(/π/g, ' \\pi ')
    .replace(/α/g, ' \\alpha ')
    .replace(/β/g, ' \\beta ')
    .replace(/γ/g, ' \\gamma ')
    .replace(/θ/g, ' \\theta ')
    .replace(/λ/g, ' \\lambda ')
    .replace(/μ/g, ' \\mu ')
    .replace(/σ/g, ' \\sigma ')
    .replace(/ω/g, ' \\omega ')
    .replace(/Δ/g, ' \\Delta ')
    .replace(/→/g, ' \\rightarrow ')
    .replace(/←/g, ' \\leftarrow ')
    .replace(/↔/g, ' \\leftrightarrow ')
    .replace(/⇒/g, ' \\Rightarrow ')
    .replace(/∈/g, ' \\in ')
    .replace(/∉/g, ' \\notin ')
    .replace(/⊂/g, ' \\subset ')
    .replace(/∪/g, ' \\cup ')
    .replace(/∩/g, ' \\cap ')
    .replace(/°/g, '^\\circ ')
    .replace(/·/g, ' \\cdot ')
    .replace(/√/g, ' \\sqrt{} ');
}

function getChildByLocalName(el: Element, name: string): Element | null {
  for (let i = 0; i < el.children.length; i++) {
    const child = el.children[i];
    const cLocal = child.localName || child.tagName.replace(/^.*:/, '');
    if (cLocal.toLowerCase() === name.toLowerCase()) {
      return child;
    }
  }
  return null;
}

function getLeftFence(chr: string): string {
  if (chr === '(') return '\\left(';
  if (chr === '[') return '\\left[';
  if (chr === '{') return '\\left\\{';
  if (chr === '|') return '\\left|';
  if (chr === '‖') return '\\left\\|';
  if (!chr) return '\\left.';
  return `\\left${chr}`;
}

function getRightFence(chr: string): string {
  if (chr === ')') return '\\right)';
  if (chr === ']') return '\\right]';
  if (chr === '}') return '\\right\\}';
  if (chr === '|') return '\\right|';
  if (chr === '‖') return '\\right\\|';
  if (!chr) return '\\right.';
  return `\\right${chr}`;
}

function mapNaryOperator(chr: string): string {
  if (chr === '∑') return '\\sum';
  if (chr === '∫') return '\\int';
  if (chr === '∬') return '\\iint';
  if (chr === '∭') return '\\iiint';
  if (chr === '∮') return '\\oint';
  if (chr === '∏') return '\\prod';
  if (chr === '⋃') return '\\bigcup';
  if (chr === '⋂') return '\\bigcap';
  return '\\sum';
}

function mapFunctionName(fn: string): string {
  const standard = [
    'sin', 'cos', 'tan', 'cot', 'sec', 'csc',
    'arcsin', 'arccos', 'arctan',
    'sinh', 'cosh', 'tanh',
    'log', 'ln', 'lg', 'exp', 'det', 'gcd', 'max', 'min', 'lim'
  ];
  if (standard.includes(fn.toLowerCase())) {
    return `\\${fn.toLowerCase()}`;
  }
  return `\\operatorname{${fn}}`;
}

/**
 * Recursively converts an Office Math Markup Language (OMML) XML Node to LaTeX.
 */
export function ommlNodeToLatex(node: Node): string {
  if (node.nodeType === Node.TEXT_NODE) {
    return node.textContent || '';
  }
  if (node.nodeType !== Node.ELEMENT_NODE) {
    return '';
  }

  const el = node as Element;
  const localName = (el.localName || el.tagName.replace(/^.*:/, '')).toLowerCase();

  switch (localName) {
    case 'omathpara':
    case 'omath': {
      let res = '';
      for (let i = 0; i < el.childNodes.length; i++) {
        res += ommlNodeToLatex(el.childNodes[i]);
      }
      return res;
    }

    case 'r': {
      // Math run - contains m:t (math text)
      let text = '';
      for (let i = 0; i < el.childNodes.length; i++) {
        const child = el.childNodes[i];
        if (child.nodeType === Node.ELEMENT_NODE) {
          const cName = ((child as Element).localName || (child as Element).tagName.replace(/^.*:/, '')).toLowerCase();
          if (cName === 't') {
            text += child.textContent || '';
          }
        }
      }
      if (!text) {
        text = el.textContent || '';
      }
      return mapOmmlTextToLatex(text);
    }

    case 't': {
      return mapOmmlTextToLatex(el.textContent || '');
    }

    case 'f': {
      // Fraction: num / den
      const num = getChildByLocalName(el, 'num');
      const den = getChildByLocalName(el, 'den');
      const numLatex = num ? ommlNodeToLatex(num).trim() : '';
      const denLatex = den ? ommlNodeToLatex(den).trim() : '';
      return `\\frac{${numLatex}}{${denLatex}}`;
    }

    case 'num':
    case 'den':
    case 'e': {
      let res = '';
      for (let i = 0; i < el.childNodes.length; i++) {
        res += ommlNodeToLatex(el.childNodes[i]);
      }
      return res;
    }

    case 'ssup': {
      // Superscript: e ^ sup
      const base = getChildByLocalName(el, 'e');
      const sup = getChildByLocalName(el, 'sup');
      const baseLatex = base ? ommlNodeToLatex(base) : '';
      const supLatex = sup ? ommlNodeToLatex(sup).trim() : '';
      return `{${baseLatex}}^{${supLatex}}`;
    }

    case 'ssub': {
      // Subscript: e _ sub
      const base = getChildByLocalName(el, 'e');
      const sub = getChildByLocalName(el, 'sub');
      const baseLatex = base ? ommlNodeToLatex(base) : '';
      const subLatex = sub ? ommlNodeToLatex(sub).trim() : '';
      return `{${baseLatex}}_{${subLatex}}`;
    }

    case 'ssubsup': {
      // Subscript and Superscript: e _ sub ^ sup
      const base = getChildByLocalName(el, 'e');
      const sub = getChildByLocalName(el, 'sub');
      const sup = getChildByLocalName(el, 'sup');
      const baseLatex = base ? ommlNodeToLatex(base) : '';
      const subLatex = sub ? ommlNodeToLatex(sub).trim() : '';
      const supLatex = sup ? ommlNodeToLatex(sup).trim() : '';
      return `{${baseLatex}}_{${subLatex}}^{${supLatex}}`;
    }

    case 'spre': {
      // Pre-sub-superscript
      const base = getChildByLocalName(el, 'e');
      const sub = getChildByLocalName(el, 'sub');
      const sup = getChildByLocalName(el, 'sup');
      const baseLatex = base ? ommlNodeToLatex(base) : '';
      const subLatex = sub ? ommlNodeToLatex(sub).trim() : '';
      const supLatex = sup ? ommlNodeToLatex(sup).trim() : '';
      return `{}_{${subLatex}}^{${supLatex}}{${baseLatex}}`;
    }

    case 'rad': {
      // Radical: \sqrt or \sqrt[deg]
      const base = getChildByLocalName(el, 'e');
      const deg = getChildByLocalName(el, 'deg');
      const baseLatex = base ? ommlNodeToLatex(base).trim() : '';
      const degLatex = deg ? ommlNodeToLatex(deg).trim() : '';
      if (degLatex) {
        return `\\sqrt[${degLatex}]{${baseLatex}}`;
      }
      return `\\sqrt{${baseLatex}}`;
    }

    case 'd': {
      // Delimiter: (e) or [e] or {e} or |e|
      const dPr = getChildByLocalName(el, 'dPr');
      let begChr = '(';
      let endChr = ')';
      if (dPr) {
        const begNode = getChildByLocalName(dPr, 'begChr');
        const endNode = getChildByLocalName(dPr, 'endChr');
        if (begNode) {
          begChr = begNode.getAttribute('m:val') ?? begNode.getAttribute('val') ?? '(';
        }
        if (endNode) {
          endChr = endNode.getAttribute('m:val') ?? endNode.getAttribute('val') ?? ')';
        }
      }

      const leftFence = getLeftFence(begChr);
      const rightFence = getRightFence(endChr);

      const eChildren = Array.from(el.children).filter(
        c => (c.localName || c.tagName.replace(/^.*:/, '')).toLowerCase() === 'e'
      );
      if (eChildren.length > 1) {
        const joined = eChildren.map(c => ommlNodeToLatex(c).trim()).join(', ');
        return `${leftFence} ${joined} ${rightFence}`;
      }

      const base = getChildByLocalName(el, 'e');
      const baseLatex = base ? ommlNodeToLatex(base).trim() : '';
      return `${leftFence} ${baseLatex} ${rightFence}`;
    }

    case 'nary': {
      // N-ary operator: \sum, \int, \prod
      const naryPr = getChildByLocalName(el, 'naryPr');
      let chr = '∑';
      if (naryPr) {
        const chrNode = getChildByLocalName(naryPr, 'chr');
        if (chrNode) {
          chr = chrNode.getAttribute('m:val') ?? chrNode.getAttribute('val') ?? '∑';
        }
      }
      const op = mapNaryOperator(chr);
      const sub = getChildByLocalName(el, 'sub');
      const sup = getChildByLocalName(el, 'sup');
      const base = getChildByLocalName(el, 'e');

      const subLatex = sub ? ommlNodeToLatex(sub).trim() : '';
      const supLatex = sup ? ommlNodeToLatex(sup).trim() : '';
      const baseLatex = base ? ommlNodeToLatex(base).trim() : '';

      let res = op;
      if (subLatex) res += `_{${subLatex}}`;
      if (supLatex) res += `^{${supLatex}}`;
      res += ` {${baseLatex}}`;
      return res;
    }

    case 'func': {
      // Function: fName(e)
      const fName = getChildByLocalName(el, 'fName');
      const base = getChildByLocalName(el, 'e');
      const fnLatex = fName ? ommlNodeToLatex(fName).trim() : '';
      const baseLatex = base ? ommlNodeToLatex(base).trim() : '';
      return `${mapFunctionName(fnLatex)} ${baseLatex}`;
    }

    case 'limlow': {
      const base = getChildByLocalName(el, 'e');
      const lim = getChildByLocalName(el, 'lim');
      const baseLatex = base ? ommlNodeToLatex(base).trim() : '';
      const limLatex = lim ? ommlNodeToLatex(lim).trim() : '';
      return `\\lim_{${limLatex}} {${baseLatex}}`;
    }

    case 'limupp': {
      const base = getChildByLocalName(el, 'e');
      const lim = getChildByLocalName(el, 'lim');
      const baseLatex = base ? ommlNodeToLatex(base).trim() : '';
      const limLatex = lim ? ommlNodeToLatex(lim).trim() : '';
      return `\\lim^{${limLatex}} {${baseLatex}}`;
    }

    case 'm': {
      // Matrix
      const mrList = Array.from(el.children).filter(
        c => (c.localName || c.tagName.replace(/^.*:/, '')).toLowerCase() === 'mr'
      );
      const rows = mrList.map(row => {
        const cells = Array.from(row.children).filter(
          c => (c.localName || c.tagName.replace(/^.*:/, '')).toLowerCase() === 'e'
        );
        return cells.map(c => ommlNodeToLatex(c).trim()).join(' & ');
      });
      return `\\begin{matrix} ${rows.join(' \\\\ ')} \\end{matrix}`;
    }

    case 'bar': {
      const base = getChildByLocalName(el, 'e');
      const baseLatex = base ? ommlNodeToLatex(base).trim() : '';
      return `\\overline{${baseLatex}}`;
    }

    case 'acc': {
      const accPr = getChildByLocalName(el, 'accPr');
      let chr = '^';
      if (accPr) {
        const chrNode = getChildByLocalName(accPr, 'chr');
        if (chrNode) {
          chr = chrNode.getAttribute('m:val') ?? chrNode.getAttribute('val') ?? '^';
        }
      }
      const base = getChildByLocalName(el, 'e');
      const baseLatex = base ? ommlNodeToLatex(base).trim() : '';
      if (chr === '→' || chr === '⃗') return `\\vec{${baseLatex}}`;
      if (chr === '^' || chr === '̂') return `\\hat{${baseLatex}}`;
      if (chr === '.' || chr === '̇') return `\\dot{${baseLatex}}`;
      if (chr === '..' || chr === '̈') return `\\ddot{${baseLatex}}`;
      if (chr === '~' || chr === '̃') return `\\tilde{${baseLatex}}`;
      if (chr === '¯' || chr === '̄') return `\\bar{${baseLatex}}`;
      return `\\hat{${baseLatex}}`;
    }

    case 'box': {
      const base = getChildByLocalName(el, 'e');
      return base ? `{${ommlNodeToLatex(base).trim()}}` : '';
    }

    default: {
      let res = '';
      for (let i = 0; i < el.childNodes.length; i++) {
        res += ommlNodeToLatex(el.childNodes[i]);
      }
      return res;
    }
  }
}

/**
 * Preprocesses a Word (.docx) ArrayBuffer by transforming all OMML math equations
 * (`<m:oMath>` and `<m:oMathPara>`) into standard Word text runs containing LaTeX strings
 * (`$latex$` or `$$latex$$`) before passing to Mammoth.
 */
export async function preprocessDocxMath(arrayBuffer: ArrayBuffer): Promise<ArrayBuffer> {
  try {
    const zip = await JSZip.loadAsync(arrayBuffer);
    const documentXmlFile = zip.file('word/document.xml');
    if (!documentXmlFile) {
      return arrayBuffer;
    }

    const xmlContent = await documentXmlFile.async('string');
    // Fast check if there are math equations in document.xml
    if (!xmlContent.includes('<m:oMath') && !xmlContent.includes(':oMath')) {
      return arrayBuffer;
    }

    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlContent, 'application/xml');

    if (xmlDoc.getElementsByTagName('parsererror').length > 0) {
      console.warn('XML parser error in word/document.xml, skipping math preprocessing');
      return arrayBuffer;
    }

    const wNamespace = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';

    // 1. Process display equations (<m:oMathPara>)
    const mathParas = Array.from(xmlDoc.getElementsByTagNameNS('*', 'oMathPara'));
    for (const para of mathParas) {
      const latex = ommlNodeToLatex(para).trim();
      if (latex) {
        const wRun = xmlDoc.createElementNS(wNamespace, 'w:r');
        const wText = xmlDoc.createElementNS(wNamespace, 'w:t');
        wText.textContent = `$$${latex}$$`;
        wRun.appendChild(wText);
        para.parentNode?.replaceChild(wRun, para);
      }
    }

    // 2. Process inline equations (<m:oMath>)
    const mathInlines = Array.from(xmlDoc.getElementsByTagNameNS('*', 'oMath'));
    for (const math of mathInlines) {
      const latex = ommlNodeToLatex(math).trim();
      if (latex) {
        const wRun = xmlDoc.createElementNS(wNamespace, 'w:r');
        const wText = xmlDoc.createElementNS(wNamespace, 'w:t');
        wText.textContent = `$${latex}$`;
        wRun.appendChild(wText);
        math.parentNode?.replaceChild(wRun, math);
      }
    }

    const serializer = new XMLSerializer();
    const updatedXml = serializer.serializeToString(xmlDoc);
    zip.file('word/document.xml', updatedXml);

    return await zip.generateAsync({ type: 'arraybuffer' });
  } catch (err) {
    console.warn('Docx math preprocessing fallback to original buffer:', err);
    return arrayBuffer;
  }
}
